<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TestFunctionBlock" Id="{d572f337-29d2-46df-a865-e75df6da31ee}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TestFunctionBlock
VAR
	nCounter : LINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nCounter := nCounter + 1;]]></ST>
    </Implementation>
    <LineIds Name="FB_TestFunctionBlock">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>