<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{e02ffb5a-bf0c-4392-8a13-b0306996ad4d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbFactorial : IO.Factorial;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbFactorial(); ]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>